package com.agentfit.coreapi.catalog;

import com.agentfit.coreapi.configuration.export.StoredPreviewState;
import com.agentfit.coreapi.configuration.preview.PreviewBasis;
import com.agentfit.coreapi.configuration.preview.PreviewFingerprintResult;
import com.agentfit.coreapi.recommendation.EnvironmentTarget;
import com.agentfit.coreapi.recommendation.selection.PermissionSelection;
import com.agentfit.coreapi.recommendation.selection.StoredRecommendationState;
import java.util.List;
import java.util.Objects;

/**
 * B's Preview creation boundary. Existing files and generated content stay transient;
 * only content-free metadata crosses the A persistence port.
 */
public final class PreviewCreationService {
    /** A authenticates and checks ownership before returning one consistent current snapshot. */
    public interface TrustedContextReader {
        TrustedContext load(String projectId, String recommendationId);
    }

    /** A rechecks current basis, recommendation, and environment in one save transaction. */
    public interface PreviewStore {
        StoredPreviewState saveIfUnchanged(TrustedContext context, Draft draft);
    }

    public record TrustedContext(PreviewBasis currentBasis, EnvironmentTarget currentTarget,
                                 StoredRecommendationState recommendation) {}

    /** No generated bytes, supplied originals, or Diff may be persisted from this record. */
    public record Draft(PreviewBasis basis, String recommendationId,
                        List<String> selectedToolKeys, List<PermissionSelection> policies,
                        String generatorVersion, String selectionDigest,
                        String contentDigest, String fingerprint) {
        public Draft {
            selectedToolKeys = List.copyOf(selectedToolKeys);
            policies = List.copyOf(policies);
        }
    }

    public record Created(StoredPreviewState saved, PreviewFingerprintResult preview) {}

    private final TrustedContextReader contexts;
    private final RecommendationCreationService.ApprovedCatalogReader catalogs;
    private final PreviewStore store;

    public PreviewCreationService(TrustedContextReader contexts,
                                  RecommendationCreationService.ApprovedCatalogReader catalogs,
                                  PreviewStore store) {
        this.contexts = Objects.requireNonNull(contexts);
        this.catalogs = Objects.requireNonNull(catalogs);
        this.store = Objects.requireNonNull(store);
    }

    public Created create(String projectId, CatalogPreviewRequest request) {
        if (projectId == null || projectId.isBlank() || request == null
            || request.recommendationId() == null || request.recommendationId().isBlank()) {
            throw new IllegalArgumentException("project and recommendation required");
        }
        TrustedContext context = Objects.requireNonNull(
            contexts.load(projectId, request.recommendationId()));
        if (context.currentBasis() == null
            || !projectId.equals(context.currentBasis().projectId())) {
            throw new IllegalArgumentException("Preview context belongs to another project");
        }
        var catalog = Objects.requireNonNull(catalogs.current());
        PreviewFingerprintResult preview = CatalogPreviewAssembler.assemble(
            catalog.directory(), catalog.approvedHash(), context.recommendation(),
            context.currentBasis(), context.currentTarget(), request);
        Draft draft = new Draft(context.currentBasis(), request.recommendationId(),
            request.selectedToolKeys(), request.permissionSelections(), request.generatorVersion(),
            preview.selectionDigest(), preview.contentDigest(), preview.fingerprint());
        StoredPreviewState saved = store.saveIfUnchanged(context, draft);
        if (saved == null || saved.previewId() == null || saved.previewId().isBlank()
            || !context.currentBasis().equals(saved.basis())
            || !preview.fingerprint().equals(saved.fingerprint())
            || saved.expiresAt() == null) {
            throw new IllegalStateException("Preview metadata was not saved correctly");
        }
        return new Created(saved, preview);
    }
}
